### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by charlesfoster** [cihga39871/Atria#11]
Hi,
I'm trying out `atria`. I ran the program like so:

```
atria --detect-adapter --no-quality-trim --no-length-filtration -o test -t 8 -r  $R1 -R $R2
```

Printed to terminal is:

```
pigz 2.6
┌ Info: ACV_REP1_1.merged.fastq.gz:
└  No adapter detected in the first 304797 reads.
┌ Info: ACV_REP1_2.merged.fastq.gz:
│  Top 5 adapters detected in the first 304693 reads:
│ ┌──────────────────┬───────────┬──────────┐
│ │          Adapter │ Occurance │ Identity │
│ ├──────────────────┼───────────┼──────────┤
│ │ CTGCCCCGGGTTCCTC │       127 │ 0.917323 │
│ │ GTGACTGGAGTTCAGA │        61 │ 0.928279 │
│ │ CAAGCAGAAGACGGCA │        60 │ 0.930208 │
│ │ CTGTCTCTTATACACA │        60 │ 0.928125 │
│ │ ACACTCTTTCCCTACA │        57 │ 0.947368 │
└ └──────────────────┴───────────┴──────────┘
```

However, when I check the output directory, it's empty. Any clues?

Details:
- Pop!_OS 22.04 LTS x86_64
- atria v3.2.1 (downloaded from https://github.com/cihga39871/Atria/releases/download/v3.2.1/atria-3.2.1-linux-ubuntu22_glibc2.34.tar.gz)

Thanks

**Comment by cihga39871** [comment]
Hi, `--detect-adapter` means only displaying possible adapter sequences, and do not do any trimming. You need to choose the correct adapter, and use 

```bash
atria --no-quality-trim --no-length-filtration -o test -t 8 -r $R1 -R $R2 -a ADAPTER1 -A ADAPTER2
```

Atria does not help users decide which adapter to remove. From my NGS experience, it is better to manually check the correct adapter content, and relying on a black box sometimes causes problems.

For your data, your adapter sequences were likely pre-trimmed, so we cannot detect adapter contents in R1, and the adapter identity in R2 is only 91%, which is lower than expected. In this case, it is better to contact the person who prepared the library.

**Comment by charlesfoster** [comment]
Thanks, makes sense. I naively thought that `atria` would act like `fastp` and detect then trim in one step.
