### ISSUE TITLE
Error during initialization of module CHOLMOD

### ISSUE THREAD

**Issue by jdm204** [cihga39871/Atria#16]
Hi, thanks for the tool and maintaining it!

I just ran it for the first time, and it output trimmed reads, but the initial output contains this error:

```
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load library "libcholmod"
│    libamd.so.2: cannot open shared object file: No such file or directory
│    Stacktrace:
│     [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
│       @ Base.Libc.Libdl ./libdl.jl:117
│     [2] dlopen (repeats 2 times)
│       @ ./libdl.jl:116 [inlined]
│     [3] __init__()
│       @ SuiteSparse.CHOLMOD ~/scratch/atria/atria-4.0.3/share/julia/stdlib/v1.8/SuiteSparse/src/cholmod.jl:161
└ @ SuiteSparse.CHOLMOD /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/SuiteSparse/src/cholmod.jl:245
```

I'm not familiar with the code so unsure if this is a serious issue that will affect the output, as the tools did finish on my reads.

Here is the atria information:

```
pigz 2.8
┌ Info: ATRIA VERSIONS
│   atria = "v4.0.3"
└   julia = "v1.8.5"
┌ Info: ATRIA ARGUMENTS
└   command = `-t 4 --polyG -r LH20_blood_EKDN240004237-1A_2237NFLT4_L4_1.fq.gz -R LH20_blood_EKDN240004237-1A_2237NFLT4_L4_2.fq.gz`
┌ Info: ATRIA OUTPUT FILES
│   read1 = "/home/jdm204/scratch/atria/LH20_blood_EKDN240004237-1A_2237NFLT4_L4_1.atria.fq.gz"
└   read2 = "/home/jdm204/scratch/atria/LH20_blood_EKDN240004237-1A_2237NFLT4_L4_2.atria.fq.gz"
┌ Info: ATRIA TRIMMERS AND FILTERS
│   adapter_trimming = true
│   consensus_calling = true
│   hard_clip_3_end_r1 = false
│   hard_clip_3_end_r2 = false
│   hard_clip_5_end_r1 = false
│   hard_clip_5_end_r2 = false
│   quality_trimming = true
│   tail_N_trimming = true
│   max_N_filtering = true
└   length_filtering = true
```

**Comment by cihga39871** [comment]
Hello, thank you for your interest in Atria and report this issue!

I am sorry that you have been found this error. You are right, it **does not affect any function of Atria**.

It is fixed in the latest version. You can download in the release page or build from source to avoid this message.

The error was introduced by a third party package called 'PackageCompiler'. If you want to know some details, you can check this [link](https://github.com/JuliaLang/PackageCompiler.jl/issues/925).

Have a great day,
Eric

**Comment by asan-emirsaleh** [comment]
Hello @cihga39871  ! Thank you for your efforts in open source science advancing and software development!
I wish to notice that I also have the same error in atria v4.1.1.
