### ISSUE TITLE
Multiple adapter specifying

### ISSUE THREAD

**Issue by asan-emirsaleh** [cihga39871/Atria#4]
Hello!
Amazing job! Thank you a lot for you this tool to create!

I have a question on specifying multiple adapter.
While doing round with --detect-adapter, the result would contain four strings for each direction. The are much shorter than default adapter sequences and several bases are different. Do I have to specify them all? How to specify multiple adapter seqs?

Best regards
Asan

**Comment by cihga39871** [comment]
Thank you for the question.
Atria only detect the first 16 bp of adapters, which is enough for our algorithm to get best results.
Usually a sample only contain one adapter, you can choose the adapter with the highest occurrence. We do not need to specify multiple adapters for one sample.
