### ISSUE TITLE
More benchmark against existing tools

### ISSUE THREAD

**Issue by cnzqy1** [cihga39871/Atria#5]
Thanks a lot for your tool! [BBDuk](https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/bbduk-guide/) can also do paired end adapter trimming, and I'm curious about how this tool compares against it. Could you also include BBDuk in your benchmark?

**Comment by cihga39871** [comment]
It is a nice suggestion. I'd like to add them later.
