### ISSUE TITLE
Has Atria been tested on CUT&RUN data?

### ISSUE THREAD

**Issue by c5creative** [cihga39871/Atria#9]
Greetings - very nice work and paper. I was wondering if anyone has tried Atria for CUT&RUN and if so, what parameters/results have been obtained. Thank you! JP

**Comment by cihga39871** [comment]
Hi JP, thank you for the interest on Atria.

You can use Atria happily with CUT&RUN data. The DNA refinement or processing before library preparation (CUT&RUN, CHIP, etc.) does not affect the library preparation process, so it does not affect trimming and quality control of Illumina sequences. 

Most parameters can be the same as default, but in consideration of the binding sites could be short, it is better to loose read length filtration (`--length-range 50:500`, default only output sequences between 50 to 500 bp), or you can just disable it (`--no-length-filtration`).
